[package]
description = "Standard library for Osmosis with CosmWasm support included"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "osmosis-std"
version = "0.1.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = {version = "1.0.0", features = ["stargate"]}
osmosis-std-derive = {version = "0.1.6", path = "../osmosis-std-derive"}
prost = {version = "0.10.4", default-features = false, features = ["prost-derive"]}
schemars = "0.8.8"
prost-types = {version = "0.10.1", default-features = false}

# for query
serde = {version = "1.0", default-features = false, features = ["derive"]}
